### ISSUE TITLE
Performance Upgrades

### ISSUE THREAD

**Issue by txzeenath** [Nition/UnityOctree#15]
- [x] - Combine point and bounds logic
- [x] - Object add method.
- [x] - Object remove method.
- [ ] - Object move method.
- [x] - Node splitting on-demand.
- [x] - Branch based object count tracking.
- [x] - Automatic merging of branches/leaves.
- [x] - Custom intersection tests to avoid unity internal calls.
- [x] - Get rid of dependence on unity's Bounds struct internally.
- [x] - Instance pooling.
- [x] - O(1) Object removal.
- [ ] - Implement queries into tree.
- [ ] - Implement queries from objects.
- [ ] - Eliminate recursive methods where plausible.
- [ ] - Documentation.
- [ ] - Clean up/write summaries.
- [ ] - Add queries to testing scene
- [ ] - Add queries to tree visualization

Scrapped:
Linear. Actually proved to be slower with current implementation.
Directional tree growth. Not really necessary. Proper implementation avoids this need.
Tree shrinking. As above.

**Comment by Nition** [comment]
It was quite a while ago now that I profiled the octree, but I remember the biggest performance bottleneck being simply traversing the tree between through nodes. One thing I've heard of that could make a big difference there is linearizing it: https://en.wikipedia.org/wiki/Linear_octree
Basically putting it into a big array. But it's not something I've done before myself.

You're welcome to submit pull requests for whatever, and thanks for the ones you've put through today already. I won't guarantee I'll accept everything into the main project but it's nice to have people improving the thing.

**Comment by Nition** [comment]
I'm totally happy to combine the point and bounds trees if the points tree can be as efficient as it was on its own. I think I was just worried originally that there'd be unnecessary overhead since a point tree is simpler since there's no worrying about whether a point spans nodes.

Actually even if it's slightly less efficient it's probably still worth combining them.

**Comment by txzeenath** [comment]
After you mentioned it I decided to try a linearized tree. Which is going better than expected since I really never looked into what an octree was until checking out yours. I'm just working on optimizing add/removes at the moment. Still need to implement the queries.

Current performance is about 300ms to insert 300,000 objects and 200ms to remove them all (54,788 nodes). Including time splitting/merging. It could be faster but I'm not great with the math needed to pre-calculate node positions.

**Comment by Nition** [comment]
That's awesome, man! How do those times compare to doing the same thing on your machine with the existing (not linear) version of the tree?

**Comment by txzeenath** [comment]
I still have to adapt my benchmark setup to include the other trees. Which I might do tonight. It'll give a much better idea of the gains.

I know when I was using the point tree, I was hitting 500ms or so adding/removing 8000 objects each frame (in-editor with profiler connected).

**Comment by txzeenath** [comment]
A quick test with 39,304 objects shows:

 - Adding:
- - Linearized: 50ms
- - PointTree: 63ms

 - Removing:
- - Linearized: 25ms
- - PointTree: 20193ms

I had to reduce the number of objects, as the point tree freezes once you approach 100,000 (assuming recursion). I'm using pooling in the linear version, which adds a little CPU time for lookups.

Currently only splitting single nodes at a time as well. It adds to the time on an add as I need to iterate the object list potentially 8 times per full split, but hoping it provides a speedup during traversal since child nodes only exist if they're needed. I store the existing children as a bitmask so checking for a child should be very quick.

I may switch to using two masks, one for empty children and one for children with objects. So I can cut down split time and get the benefit of not checking extra nodes during queries.

**Comment by Nition** [comment]
That remove time! Sounds great. I've always wanted to try linearising the tree but never got around to finding the time.

**Comment by txzeenath** [comment]
Main speed up on removal is because the added object is returned to the caller. You just call object.Remove(). The object holds a reference to the node it's in. So removal itself requires no traversal. 

Object counts are tracked in reverse. So if you remove/add to a node at depth 10, it only has to update 10 other nodes. I call this the "branch count" and lets every node know how many objects are below them at all times.

**Comment by txzeenath** [comment]
Tweaked some stuff in the linear version:
 - Using bitmask to tell which children have objects
 - - Don't need to do a lookup to check the node
 - Added localItemCount field
 - - Cheaper than using List.Count
 - Added parent reference to nodes
 - - Cheaper than using dictionary lookups when traversing upwards
 - Splitting into 8 every time now instead of of per-octant 
- - Only iterate object list once per node split now

**New times:**
 - 39,304 Objects
 - - Add: 45ms (5ms faster)
 - - Remove: 16ms (9ms faster)

 - 300,762 Objects:
 - - Add: 230ms
 - - Remove: 130ms

And just for fun..
 - 7,880,599 Objects
 - - Add: 6.5s
 - - Remove: 3.5s

**Comment by Nition** [comment]
All that sounds logical and like good changes (although I'm not sure exactly what you mean with the "splitting into 8 every time" change TBH). I'm impressed!

**Comment by txzeenath** [comment]
Originally I was splitting one octant at a time as needed in my version in order to reduce the number of nodes checked once I add queries. But I just used a bitmask for that instead.

**Comment by txzeenath** [comment]
Was doing some profiling and noticed a lot of time spent in my bit shifting methods and dictionary lookups. So I de-linearized the tree with the existing logic and it actually made it stupid fast.

 - 39,304 Objects
 - - Add: 27ms
 - - Remove: 17ms 

 - 300,763
 - - Add: 123ms
 - - Remove: 118ms

 - 7,880,599
 - - Add: 3.5s
 - - Remove: 3.2s

I'm assuming it's a few possible factors:
 - Nodes are likely being stored on the heap, meaning the CPU cache rarely comes into play as the instances are scattered throughout.
 - Putting the children into pre-allocated arrays MIGHT be giving a small boost due to caching since they're allocated in a single "block".
 - Without using a custom dictionary with hash caching, GetHashCode actually takes a large amount of the CPU cycles, even with a primitive (uint) key type.

**Comment by Nition** [comment]
That's interesting. I just had a quick look at the code in your branch. I wonder if traversing the children on Add without using recursion makes a big difference as well. Maybe a lot of the original slowness with the original version was the recursive calls, since each recursive call in C# pushes everything onto the stack and pops it when it comes back out.

**Comment by txzeenath** [comment]
Eliminating recursion and religious abuse of the BestFitChild method definitely helped. Irrelevant nodes are never pulled from memory, and the stack isn't being obliterated.

The only place really using recursion is merge, since I can't think of a good way to drop down into multiple children without it.

**Comment by txzeenath** [comment]
Eliminated lists for tracking objects. The constant searching was a bit slow. Instead I turned each object into essentially a linked list node. Where each object has a reference to the next object and previous object in the chain. Nodes hold a reference to the first object. Removal is simply changing some references. 

Merging an entire node of objects into an empty node is just 
```
this.firstItem = other.FirstItem 
other.firstItem = null;
```
Merging a node into another when it already has objects is just (Pseudocode):
```
this.firstObject.previous = other.lastObj
other.LastObj.next = this.firstObject;
this.firstObject = other.firstObject;
```


**New times:**
 - 39,304 Objects
 - - Add: 20ms
 - - Remove: 3ms

 - 300,762 Objects:
 - - Add: 77ms
 - - Remove: 19ms

 - 7,880,599 Objects
 - - Add: 2.1s
 - - Remove: 559ms

**Comment by Nition** [comment]
Personally my current use for the octree is infrequent adds/removes, but frequent checks (IsColliding, GetNearby). So while fast add/remove is great, performance when using the complete tree is a big factor also.

I just did a quick test, converting GetNearby from using recursion to using a stack (like an actual c# stack object, not _the stack_), and it actually got a little _slower_. So much my idea of recursion being the source of all maladys. Tried the same thing on the Add method in BoundsOctreeNode and that _also_ got slightly slower. Your way is a little different of course, letting you traverse the children using `index` without the need for a stack to puch/pop from.

Just thought that was interesting.

**Comment by Antypodish** [comment]
According to txzeenath - point": "Object move method" (not complete). Is this regarding actually moving objects at runtime? 

Testing currently, I don't seam can make any efficient way, to move large amount of object (1k+), while updating boundries for boundsTree, without removing and adding object instances, so the tree boundary can be updated aswell. For example `boundsTree.Add` followed by `boundsTree.Remove`, wrapped in for loop `for ( int i = 0; i < objects.childCount; i++ )`. 

For example:

````
for ( int i = 0; i < objects.childCount; i++ )
{

     Transform transform = object.GetChild ( i ) ;
     GameObject go = transform.gameObject ;

     boundsTree.Remove ( go  ) ;
     boundsTree.Add ( go , go.GetComponent<BoxCollider> ( ).bounds ) ;

}
````

I was thinking to attempt find a way, to use this octrees dev. with Unity 2018 new Job System, utilizing multi threading.  But unless I find efficient way first, to update boundaries position at run time, I doubt I will consider this work. Any assist will be more than welcome.
