### ISSUE TITLE
Null Reference Error in "ShrinkIfPossible"

### ISSUE THREAD

**Issue by JasonRTBond** [Nition/UnityOctree#21]
I am sometimes getting a null reference error in the function 
`public PointOctreeNode<T> ShrinkIfPossible(float minLength) `

on the first line of this block
`if (objects.Count == 0 && children.Length == 0) {
      return this;
    }`

after calling PointOctree.Remove().

Attached is a screen of MonoDevelop hitting a break point in a test block I added. It appears that "objects" can have a count of 0 and "children" can be null at the same time. Note also that inserting this block appears to prevent the issue, but I'm concerned about what side effects it might have as I don't really have a good grasp of the inner workings here.

<img width="1440" alt="screen shot 2018-05-02 at 10 22 01 am" src="https://user-images.githubusercontent.com/2727461/39528915-67f9a88e-4df3-11e8-98f4-42fb85e9914a.png">

This occurs often but not always in my scenario (perhaps 30% of the time), and usually throws null reference errors for a number of frames before stopping. This is a somewhat elaborate project with a strong possibility of timing and chance influencing the scenario here.

I regret that I don't have a clean reproduction case for you :(

**Comment by Nition** [comment]
I think you've found a legitimate bug there. Looks like the `if (objects.Count == 0 && children.Length == 0)` check should also be checking whether children is null. Your `objects == null` part should be unnecessary as objects is assigned right away and never cleared.

Try this:
```
if (objects.Count == 0 && (children == null || children.Length == 0)) {
	return this;
}
```

Seeif that fixes it for you. If it seems all good, feel free to submit a pull request for the change, or I'll add it when I can.

**Comment by Nition** [comment]
All good, it's done.
