### ISSUE TITLE
BoundsOctreeNode.GetColliding can be faster

### ISSUE THREAD

**Issue by jnsprb** [Nition/UnityOctree#33]
When I was experimenting with the Octree I was able to get the search performance down by factor 10 when fiddling with the BoundsOctreeNode.GetColliding() internals. 

Specifically: 
* manually doing the bounds check (Unity Bounds allocates and is slow)
* caching the bound vectors in the node itself (Bounds.max and min are always created in the getter)
* and working with a pre-allocated list to fill in return objects.

Maybe this helps. Cheers, Jonas

```
public void GetColliding(ref Bounds checkBounds, List<T> result) {
    // Are the input bounds at least partially in this node?
    if (!bounds.Intersects(checkBounds)) {
        return;
    // ...
}

public void GetCollidingOptimized(Vector3 positionMin, Vector3 positionMax, ref int[] resultList, ref int resultIndex) {
    if (positionMax.x < BoundsMin.x || positionMin.x > BoundsMax.x) return;
    if (positionMax.y < BoundsMin.y || positionMin.y > BoundsMax.y) return;
    if (positionMax.z < BoundsMin.z || positionMin.z > BoundsMax.z) return;
    // ....
}

public struct BoundsOctreeNodeStruct<T> {
  public struct OctreeObject {
    public Vector3 BoundsMin;
    public Vector3 BoundsMax;
    // ...
```

**Comment by Nition** [comment]
Thanks, I suspect your pre-allocated list might be doing most of the work here, as I just tried your optimised bounds method + saving the boundsMin/boundsMax, and I didn't seem to see any speedup in my own basic tests. Unless I messed something up somewhere.

I'm not going to make these changes in the actual project for now but feel free to make a fork of course. I see you've made some other changes also, given that your BoundsOctreeNodeStruct and OctreeObject  are structs.
