### ISSUE TITLE
Does growing actually work?

### ISSUE THREAD

**Issue by WazWaz** [Nition/UnityOctree#5]
If my initialWorldSize was not large enough to include all the points I added, the resulting Octree did not appear to always correctly store the points. Calling GetNearby with a ray *at* the position of the point and a small maxDistance did not always find that point.

**Comment by Nition** [comment]
I've checked this out but this one seems to work for me (barring the maxDistance bug from issue #6), so I'm afraid you might need to track this one down yourself.

**Comment by Nition** [comment]
Closing this issue since it's been a year.
