### ISSUE TITLE
Possible bug with maxDistance

### ISSUE THREAD

**Issue by WazWaz** [Nition/UnityOctree#6]
>        bounds.Expand(new Vector3(maxDistance, maxDistance, maxDistance));

Shouldn't these be maxDistance*2, since Expand increases the size, but only 1/2 in each of 6 directions?

I noticed this while implementing a GetNearby(Vector3 point) version, not actually seeing a bug from it.

**Comment by Nition** [comment]
Just checked the code. I think you're absolutely right. I'll check out your other bug report soon as well.
