### ISSUE TITLE
Shrink Problem

### ISSUE THREAD

**Issue by feixuwu** [Nition/UnityOctree#8]
When  remove an object, my excute Shrink,
Shink will change the root node, but the objects in the old root losted.

**Comment by Nition** [comment]
Hi

Would it be possible to attach a simple Unity project that reproduces the problem? It seems to work in my own test project, but if you've got one where it breaks I could check it out.

**Comment by davidebarbieri** [comment]
the english was bad, but he was right..

**Comment by Nition** [comment]
I wasn't able to reproduce this one in my test project, or see anything obviously off in the code. If anyone's able to make a simple Unity project that reproduces the bug, I'm happy to check it out.

**Comment by Nition** [comment]
Update and try now. Objects should now always reside in the deepest possible child, which should fix the shrink losing objects bug.
